"""Excel exporter tests — load the generated bytes back via openpyxl
and assert key cells. No string-compare of formatting (brittle); only
structural + value checks.
"""

from __future__ import annotations

import io

from openpyxl import load_workbook

from domains.orders.financials.computation import CostItemInput, compute_pnl
from domains.orders.financials.currency import FxRate
from domains.orders.financials.excel_export import export_pnl_xlsx


def _build_pnl_dict() -> dict:
    pnl = compute_pnl(
        match_results=[
            {
                "product_code": "A1",
                "product_name": "Apple",
                "quantity": 10,
                "unit_price": 100.0,
                "matched_product": {"supplier_id": 1, "price": 60.0},
            },
        ],
        order_currency="JPY",
        cost_items=[
            CostItemInput(id=1, category="运费", amount=100.0, currency="CNY"),
        ],
        rates=[FxRate("CNY", "JPY", 21.0)],
        tax_rate=0.06,
    )
    out = pnl.to_dict()
    out["meta"] = {
        "order_id": 1,
        "po_number": "PO-TEST-001",
        "ship_name": "MV Tester",
        "status": "ready",
        "delivery_date": "2026-06-15",
    }
    return out


def test_export_produces_three_sheets():
    blob = export_pnl_xlsx(_build_pnl_dict())
    wb = load_workbook(filename=io.BytesIO(blob))
    assert wb.sheetnames == ["利润摘要", "成本费用", "产品明细"]


def test_summary_sheet_contains_key_numbers():
    blob = export_pnl_xlsx(_build_pnl_dict())
    wb = load_workbook(filename=io.BytesIO(blob))
    ws = wb["利润摘要"]
    # Walk column A → find labels, assert column B value
    label_to_value = {ws.cell(r, 1).value: ws.cell(r, 2).value for r in range(1, ws.max_row + 1)}
    assert label_to_value["订单号"] == "PO-TEST-001"
    assert label_to_value["显示币种"] == "JPY"
    # Revenue = 10 * 100 = 1000
    assert label_to_value["产品总金额（收入）"] == 1000.0
    # Product cost = 10 * 60 = 600; freight 100 CNY * 21 = 2100; total = 2700
    assert label_to_value["产品成本"] == 600.0
    assert label_to_value["其他费用合计"] == 2100.0


def test_cost_items_sheet_has_header_and_rows():
    blob = export_pnl_xlsx(_build_pnl_dict())
    wb = load_workbook(filename=io.BytesIO(blob))
    ws = wb["成本费用"]
    headers = [ws.cell(1, c).value for c in range(1, 8)]
    assert "类别" in headers
    assert any("折算" in h for h in headers if h)
    # Row 2 is the single freight item
    assert ws.cell(2, 2).value == "运费"
    assert ws.cell(2, 3).value == "CNY"
    assert ws.cell(2, 4).value == 100.0


def test_products_sheet_includes_total_row():
    blob = export_pnl_xlsx(_build_pnl_dict())
    wb = load_workbook(filename=io.BytesIO(blob))
    ws = wb["产品明细"]
    # 1 product line → row 2 data, row 3 totals
    assert ws.cell(2, 3).value == "Apple"
    # Totals row exists with label 合计
    found_total = False
    for r in range(1, ws.max_row + 1):
        if ws.cell(r, 1).value == "合计":
            found_total = True
            break
    assert found_total
