"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { toast } from "sonner";
import {
  ArrowLeft,
  ArrowUpRight,
  Check,
  ChevronDown,
  ChevronRight,
  Folder,
  Loader2,
  MoreHorizontal,
  Pencil,
  RotateCcw,
  Trash2,
  X,
} from "lucide-react";
import {
  addUserTag,
  createOrderFromDocument,
  deleteDocument,
  getDocument,
  getDocumentOrderPayload,
  listFolders,
  moveDocumentToFolder,
  reextractDocument,
  removeUserTag,
  renameDocument,
  updateDocumentType,
  updateDocumentMetadata,
  type DocumentDetail,
  type DocumentFolder,
  type DocumentStatus,
  type OrderPayload,
  type SupportedDocType,
} from "@/lib/documents-api";
import {
  cancelChatAgent,
  createChatSession,
  sendChatMessage,
  streamChatMessages,
  type ChatMessage,
} from "@/lib/chat-api";
import { folderColor } from "@/lib/folder-color";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { MarkdownContent } from "@/components/markdown-content";
import { SpreadsheetViewer } from "@/components/spreadsheet-viewer";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";

const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8001";

// Module-level cache keyed by document id — survives client-side navigation.
// Gives instant paint on revisit; background re-fetch silently updates state.
// The document detail slice is stored in the shared documents-cache module
// so logout can wipe it in one place; the alias below keeps existing
// `.get/.set/.has` call sites working without a mass edit.
import {
  getCachedDocumentDetail,
  setCachedDocumentDetail,
} from "@/lib/documents-cache";
const _docCache = {
  get: (id: number) => getCachedDocumentDetail(id),
  set: (id: number, doc: DocumentDetail) => setCachedDocumentDetail(id, doc),
  has: (id: number) => getCachedDocumentDetail(id) !== undefined,
};
const _payloadCache = new Map<number, OrderPayload | null>();

const STATUS_DOT: Record<DocumentStatus, { label: string; dot: string; pulse?: boolean }> = {
  uploaded: { label: "排队中", dot: "bg-muted-foreground/40", pulse: true },
  extracting: { label: "提取中", dot: "bg-muted-foreground/60", pulse: true },
  extracted: { label: "已提取", dot: "bg-foreground/70" },
  error: { label: "失败", dot: "bg-red-500" },
};

// Friendlier labels for the metadata description list
const META_LABELS: Record<string, string> = {
  po_number: "PO 号",
  ship_name: "船名",
  vendor_name: "供应商",
  delivery_date: "交货日期",
  order_date: "下单日期",
  currency: "币种",
  destination_port: "目的港",
  total_amount: "总金额",
};

const META_ORDER = [
  "po_number",
  "ship_name",
  "vendor_name",
  "delivery_date",
  "order_date",
  "currency",
  "destination_port",
  "total_amount",
];

// ─── DocumentSummaryCard — AI summary + tag chips ────────────────────────
//
// Three chip styles, ordered by intent:
//   • System tags (`key:value` shape, e.g. `file_type:pdf`) — muted/mono.
//     Deterministic, derived from doc columns.
//   • LLM topic tags (bare strings, e.g. `celebrity-cruise`) — light bg.
//     Generated by the summarizer (regenerated on re-extract).
//   • User tags (manually added) — blue with X button to remove.
//     Survive re-extract. Add via the "+ 添加" input below.
//
// `summary` is rendered as plain prose paragraphs (the model is asked
// to return prose without markdown formatting).

function DocumentSummaryCard({
  summary,
  tags,
  userTags,
  onAddTag,
  onRemoveTag,
}: {
  summary: string | null;
  tags: string[];
  userTags: string[];
  onAddTag: (tag: string) => Promise<void>;
  onRemoveTag: (tag: string) => Promise<void>;
}) {
  const systemTags = tags.filter((t) => t.includes(":"));
  const topicTags = tags.filter((t) => !t.includes(":"));
  const [adding, setAdding] = useState(false);
  const [draft, setDraft] = useState("");
  const [pending, setPending] = useState(false);

  async function handleSubmit(e?: React.FormEvent) {
    if (e) e.preventDefault();
    const value = draft.trim();
    if (!value) {
      setAdding(false);
      return;
    }
    setPending(true);
    try {
      await onAddTag(value);
      setDraft("");
      setAdding(false);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "添加 tag 失败");
    } finally {
      setPending(false);
    }
  }

  async function handleRemove(tag: string) {
    setPending(true);
    try {
      await onRemoveTag(tag);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "删除 tag 失败");
    } finally {
      setPending(false);
    }
  }

  return (
    <section className="space-y-4 rounded-md border border-border/60 bg-muted/20 p-5">
      <div className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
        AI 摘要
      </div>
      {summary ? (
        <div className="space-y-2 text-sm leading-6 text-foreground/90">
          {summary.split(/\n\n+/).map((para, i) => (
            <p key={i}>{para.trim()}</p>
          ))}
        </div>
      ) : (
        <p className="text-xs text-muted-foreground">（无摘要）</p>
      )}

      <div className="flex flex-wrap items-center gap-1.5 pt-1">
        {systemTags.map((t) => (
          <span
            key={t}
            className="rounded-full bg-muted px-2.5 py-0.5 font-mono text-[10px] text-muted-foreground"
            title="系统 tag"
          >
            {t}
          </span>
        ))}
        {topicTags.map((t) => (
          <span
            key={t}
            className="rounded-full bg-foreground/5 px-2.5 py-0.5 text-[11px] text-foreground/80"
            title="内容 tag"
          >
            {t}
          </span>
        ))}
        {userTags.map((t) => (
          <span
            key={t}
            className="inline-flex items-center gap-1 rounded-full bg-blue-100 px-2.5 py-0.5 text-[11px] font-medium text-blue-700 dark:bg-blue-950/40 dark:text-blue-300"
            title="我添加的 tag"
          >
            {t}
            <button
              type="button"
              disabled={pending}
              onClick={() => handleRemove(t)}
              className="ml-0.5 inline-flex h-3 w-3 items-center justify-center rounded-full hover:bg-blue-200/60 disabled:opacity-50 dark:hover:bg-blue-800/40"
              aria-label={`删除 tag ${t}`}
            >
              <X className="h-2.5 w-2.5" />
            </button>
          </span>
        ))}

        {adding ? (
          <form onSubmit={handleSubmit} className="inline-flex items-center gap-1">
            <input
              autoFocus
              value={draft}
              onChange={(e) => setDraft(e.target.value)}
              onBlur={() => {
                if (!draft.trim()) setAdding(false);
              }}
              onKeyDown={(e) => {
                if (e.key === "Escape") {
                  setDraft("");
                  setAdding(false);
                }
              }}
              disabled={pending}
              placeholder="新 tag（回车提交）"
              className="h-6 rounded-full border border-border/60 bg-background px-2.5 text-[11px] focus:border-blue-400 focus:outline-none"
            />
          </form>
        ) : (
          <button
            type="button"
            onClick={() => setAdding(true)}
            className="inline-flex items-center gap-1 rounded-full border border-dashed border-border/60 px-2.5 py-0.5 text-[11px] text-muted-foreground hover:border-foreground/40 hover:text-foreground"
          >
            + 添加
          </button>
        )}
      </div>
    </section>
  );
}


function StatusDot({ status }: { status: DocumentStatus }) {
  const cfg = STATUS_DOT[status];
  return (
    <span className="inline-flex items-center gap-1.5 text-xs text-muted-foreground">
      <span className="relative inline-flex h-1.5 w-1.5">
        <span className={`relative inline-flex h-1.5 w-1.5 rounded-full ${cfg.dot}`} />
        {cfg.pulse ? (
          <span className={`absolute inset-0 inline-flex animate-ping rounded-full opacity-60 ${cfg.dot}`} />
        ) : null}
      </span>
      <span className="text-foreground/80">{cfg.label}</span>
    </span>
  );
}

const toUTC = (s: string) => s.endsWith("Z") || s.includes("+") ? s : s + "Z";
function formatTime(iso: string | null) {
  if (!iso) return "—";
  return new Date(toUTC(iso)).toLocaleString("zh-CN", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function resolvePreviewUrl(url: string | null) {
  if (!url) return null;
  if (url.startsWith("http://") || url.startsWith("https://")) return url;
  return `${API_BASE}${url}`;
}

// Backend file_type tags for spreadsheet-shaped binaries. Mirrors
// FILE_TYPE_TO_MIME in v3_backend/domains/document/file_types.py — "xlsx"
// kept for legacy rows pre-2026-05-01.
const SPREADSHEET_FILE_TYPES = new Set(["excel", "xlsx", "xls", "csv"]);
function isSpreadsheetType(t: string | null | undefined): boolean {
  return !!t && SPREADSHEET_FILE_TYPES.has(t);
}

function formatMetaValue(key: string, value: unknown): string {
  if (value === null || value === undefined || value === "") return "—";
  if (key === "total_amount" && typeof value === "number") {
    return value.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  }
  if (typeof value === "object") {
    // extra_fields or nested objects — pretty-print as JSON
    try {
      const s = JSON.stringify(value, null, 2);
      return s === "{}" || s === "[]" ? "—" : s;
    } catch {
      return "—";
    }
  }
  return String(value);
}

export default function DocumentDetailPage() {
  const params = useParams();
  const router = useRouter();
  const documentId = Number(params.id);

  const [document, setDocument] = useState<DocumentDetail | null>(_docCache.get(documentId) ?? null);
  const [payload, setPayload] = useState<OrderPayload | null>(_payloadCache.has(documentId) ? _payloadCache.get(documentId)! : null);
  // Skip skeleton if we already have cached data
  const [loading, setLoading] = useState(!_docCache.has(documentId));

  // Stable preview URL: locked once set so polls with new signed URLs don't reload the iframe
  const stablePreviewUrlRef = useRef<string | null>(
    _docCache.get(documentId)?.preview_url
      ? resolvePreviewUrl(_docCache.get(documentId)!.preview_url)
      : null
  );
  const [stablePreviewUrl, setStablePreviewUrl] = useState<string | null>(stablePreviewUrlRef.current);

  // Inline metadata editing
  const [editingMeta, setEditingMeta] = useState(false);
  const [editFields, setEditFields] = useState<Record<string, string>>({});
  const [savingMeta, setSavingMeta] = useState(false);

  // Pre-flight: inline fill of missing required fields before launching agent
  const [preFlightFields, setPreFlightFields] = useState<Record<string, string>>({});
  const [savingPreFlight, setSavingPreFlight] = useState(false);
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [extractedOpen, setExtractedOpen] = useState(false);
  const [updatingType, setUpdatingType] = useState(false);
  // Retry-button state for the "提取失败" terminal. Distinct from
  // updatingType so a retry doesn't disable the doc-type override.
  const [retrying, setRetrying] = useState(false);
  // Live elapsed-time counter shown in the "AI 提取中" progress card.
  // Resets to 0 every time the doc enters extracting/uploaded (the
  // counter restarts on doc-type change → background re-enrichment).
  const extractingStartedAtRef = useRef<number | null>(null);
  const [extractingElapsed, setExtractingElapsed] = useState(0);

  // Inline Agent state — runs the process-document skill on this page,
  // streams thinking/tool calls/results into the right sidebar instead of
  // navigating away to /dashboard/workspace.
  type AgentStatus = "idle" | "running" | "stopping" | "done" | "error";
  const [agentStatus, setAgentStatus] = useState<AgentStatus>("idle");
  const [agentMessages, setAgentMessages] = useState<ChatMessage[]>([]);
  const [agentSessionId, setAgentSessionId] = useState<string | null>(null);
  const [agentError, setAgentError] = useState<string | null>(null);
  const [agentStartedAt, setAgentStartedAt] = useState<number | null>(null);
  const [agentElapsed, setAgentElapsed] = useState(0);
  const [agentInput, setAgentInput] = useState("");
  const streamAbortRef = useRef<(() => void) | null>(null);
  const activityScrollRef = useRef<HTMLDivElement | null>(null);
  const agentBusy = agentStatus === "running" || agentStatus === "stopping";

  const fetchDocument = useCallback(async () => {
    const detail = await getDocument(documentId);
    _docCache.set(documentId, detail);

    // Lock preview URL once we have one — signed URLs change on each fetch
    // which would cause the iframe to reload. Once locked, never update.
    if (detail.preview_url && !stablePreviewUrlRef.current) {
      const resolved = resolvePreviewUrl(detail.preview_url);
      stablePreviewUrlRef.current = resolved;
      setStablePreviewUrl(resolved);
    }

    // Only replace document state when something meaningful actually changed.
    // Returning the previous reference means React skips the re-render entirely,
    // which eliminates the iframe flash caused by polling.
    let didChange = false;
    setDocument(prev => {
      if (
        prev?.status === detail.status &&
        prev?.updated_at === detail.updated_at &&
        prev?.linked_order_id === detail.linked_order_id &&
        prev?.processing_error === detail.processing_error
      ) {
        return prev; // same state → no re-render, no iframe flash
      }
      didChange = true;
      return detail;
    });

    // Only re-fetch the order payload when the document actually changed
    if (didChange) {
      if (detail.status === "extracted" && detail.doc_type === "purchase_order") {
        try {
          const currentPayload = await getDocumentOrderPayload(documentId);
          _payloadCache.set(documentId, currentPayload);
          setPayload(currentPayload);
        } catch {
          _payloadCache.set(documentId, null);
          setPayload(null);
        }
      } else {
        _payloadCache.set(documentId, null);
        setPayload(null);
      }
    }

    return detail;
  }, [documentId]);

  // Polling loop. Depends on `document?.status` so that a status flip
  // BACK into "extracting" (e.g. the user clicks "这是订单" which routes
  // through the async enrichment background job) re-arms the polling
  // chain. Without this dep, the chain stops at the first terminal state
  // and never restarts — the doc-type async refactor (2026-06-22) would
  // otherwise leave the UI spinning on a stale "extracting" snapshot
  // because `setDocument(updated)` doesn't itself trigger any poller.
  //
  // The downstream `setDocument` in fetchDocument is a no-op when
  // status/updated_at are unchanged (identity-stable return), so polling
  // ticks that don't change state DON'T trigger a useEffect re-run —
  // the only re-runs come from real status transitions.
  const documentStatus = document?.status;
  useEffect(() => {
    let cancelled = false;
    let timer: ReturnType<typeof setTimeout> | null = null;

    const run = async () => {
      try {
        const detail = await fetchDocument();
        if (cancelled) return;
        setLoading(false);
        const awaitingAutomaticOrder =
          detail.status === "extracted" &&
          detail.doc_type === "purchase_order" &&
          !detail.linked_order_id &&
          !detail.processing_error;
        if (
          detail.status === "uploaded" ||
          detail.status === "extracting" ||
          awaitingAutomaticOrder
        ) {
          timer = setTimeout(run, 1500);
        }
      } catch (error) {
        if (cancelled) return;
        setLoading(false);
        toast.error(error instanceof Error ? error.message : "加载文档失败");
      }
    };

    run();
    return () => {
      cancelled = true;
      if (timer) clearTimeout(timer);
    };
  }, [fetchDocument, documentStatus]);

  // Elapsed-time ticker for the AI 提取中 progress card. Lives in its
  // own useEffect so the polling loop above doesn't have to know about
  // UI timing concerns.
  useEffect(() => {
    const isProc =
      document?.status === "uploaded" || document?.status === "extracting";
    if (!isProc) {
      extractingStartedAtRef.current = null;
      setExtractingElapsed(0);
      return;
    }
    if (!extractingStartedAtRef.current) {
      extractingStartedAtRef.current = Date.now();
    }
    const tick = () => {
      if (extractingStartedAtRef.current) {
        setExtractingElapsed(
          Math.floor((Date.now() - extractingStartedAtRef.current) / 1000),
        );
      }
    };
    tick();
    const id = setInterval(tick, 1000);
    return () => clearInterval(id);
  }, [document?.status]);

  // Re-run extraction (used by the "重新提取" button on the error terminal).
  // Returns immediately with status="extracting"; the polling loop and the
  // elapsed-time card take over from there.
  const handleRetryExtract = useCallback(async () => {
    if (!document || retrying) return;
    setRetrying(true);
    try {
      const updated = await reextractDocument(document.id);
      setDocument(updated);
      toast.info("已开始重新提取，请稍候");
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "重新提取失败");
    } finally {
      setRetrying(false);
    }
  }, [document, retrying]);

  const metadataPairs = useMemo(() => {
    const metadata = (document?.extracted_data?.metadata || {}) as Record<string, unknown>;
    const ordered: Array<[string, unknown]> = [];
    for (const key of META_ORDER) {
      if (metadata[key] !== undefined) ordered.push([key, metadata[key]]);
    }
    // Append any extra non-empty keys we don't have a label for
    for (const [k, v] of Object.entries(metadata)) {
      if (!META_ORDER.includes(k) && v !== null && v !== undefined && v !== "") {
        ordered.push([k, v]);
      }
    }
    return ordered;
  }, [document]);

  const productCount = (document?.extracted_data?.products || []).length;

  const extractionError = ((document?.extracted_data as Record<string, unknown> | undefined)
    ?.new_extractor_error as { kind: string; message: string } | undefined) || null;

  // Confidence verdict from the PO projector. Drives the 4-state UI.
  const confidence = document?.extracted_data?.projection?.purchase_order
    ?.confidence as Record<string, unknown> | undefined;
  const confidenceVerdict = (confidence?.verdict as string | undefined) || null;
  const confidenceScore = (confidence?.score as number | undefined) ?? null;
  const confidenceMaxScore = (confidence?.max_score as number | undefined) ?? null;

  // Manual doc_type override. The user is the final authority on what this
  // document actually is. After updating, refetch the payload so the
  // primary CTA reflects the new type. Optionally auto-continue into the
  // inline agent flow when the updated type is immediately actionable.
  const handleChangeDocType = async (
    newType: SupportedDocType,
    options?: { continueIfReady?: boolean },
  ) => {
    if (!document || newType === document.doc_type || updatingType) return;
    setUpdatingType(true);
    try {
      const updated = await updateDocumentType(document.id, newType);
      setDocument(updated);
      let newPayload: OrderPayload | null = null;
      // Refetch payload so the order-creation gate reflects the new type
      if (updated.status === "extracted" && updated.doc_type === "purchase_order") {
        try {
          newPayload = await getDocumentOrderPayload(document.id);
          setPayload(newPayload);
        } catch {
          setPayload(null);
        }
      } else {
        setPayload(null);
      }
      // Async path returns status="extracting" while Gemini enrichment
      // runs in the background (8-30s). The toast must distinguish that
      // from the sync path where extracted_data is already populated,
      // otherwise the user reads "已改为采购订单" but sees the page still
      // spinning — confusing and feels broken.
      if (updated.status === "extracting") {
        toast.info("已改为采购订单 · 正在用 AI 提取订单信息（约 10-30 秒）…");
      } else {
        toast.success(`类型已改为 ${newType === "purchase_order" ? "采购订单" : "未识别"}`);
      }

      // (order creation is handled by the pre-flight card, not triggered here)
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "类型修改失败");
    } finally {
      setUpdatingType(false);
    }
  };

  const EDITABLE_FIELDS: Array<{ key: string; label: string }> = [
    { key: "po_number", label: "PO 号" },
    { key: "ship_name", label: "船名" },
    { key: "vendor_name", label: "供应商" },
    { key: "delivery_date", label: "交货日期" },
    { key: "order_date", label: "下单日期" },
    { key: "currency", label: "币种" },
    { key: "destination_port", label: "目的港" },
    { key: "total_amount", label: "总金额" },
  ];

  const startEditMeta = () => {
    const metadata = (document?.extracted_data?.metadata || {}) as Record<string, unknown>;
    const initial: Record<string, string> = {};
    for (const { key } of EDITABLE_FIELDS) {
      const v = metadata[key];
      initial[key] = v != null ? String(v) : "";
    }
    setEditFields(initial);
    setEditingMeta(true);
  };

  const handleSaveMeta = async () => {
    if (!document) return;
    setSavingMeta(true);
    try {
      const updates: Record<string, string | null> = {};
      for (const [k, v] of Object.entries(editFields)) {
        updates[k] = v.trim() || null;
      }
      const newPayload = await updateDocumentMetadata(document.id, updates);
      _payloadCache.set(document.id, newPayload);
      setPayload(newPayload);
      // Refresh document to reflect updated extracted_data
      const refreshed = await import("@/lib/documents-api").then(m => m.getDocument(document.id));
      _docCache.set(document.id, refreshed);
      setDocument(refreshed);
      setEditingMeta(false);
      toast.success("字段已保存");
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "保存失败");
    } finally {
      setSavingMeta(false);
    }
  };

  const handleDelete = async () => {
    if (!document) return;
    const force = Boolean(document.linked_order_id);
    setDeleting(true);
    try {
      await deleteDocument(document.id, force);
      toast.success(
        force && document.linked_order_id
          ? `文档已删除，订单 #${document.linked_order_id} 已解除关联`
          : "文档已删除",
      );
      router.push("/dashboard/documents");
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "删除失败");
      setDeleting(false);
      setShowDeleteDialog(false);
    }
  };

  // Send a message to the document-processing agent IN PLACE on this page.
  // The right sidebar becomes a lightweight review console where the user can
  // iteratively correct extracted fields before deciding to continue.
  const sendDocumentAgentMessage = async (rawMessage: string) => {
    if (!document || agentBusy) return;
    const trimmed = rawMessage.trim();
    if (!trimmed) return;

    setAgentStatus("running");
    setAgentError(null);
    setAgentStartedAt(Date.now());
    setAgentElapsed(0);

    try {
      let sessionId = agentSessionId;
      if (!sessionId) {
        const session = await createChatSession(`文档 #${document.id}`);
        sessionId = session.id;
        setAgentSessionId(session.id);
        setAgentMessages([]);
      }

      const content = trimmed.startsWith("/")
        ? trimmed
        : [
            `当前文档 ID=${document.id}。`,
            `当前 linked_order_id=${document.linked_order_id ?? "none"}。`,
            `用户请求：${trimmed}`,
          ].join(" ");

      const { last_msg_id } = await sendChatMessage(
        sessionId,
        content,
        null,
        "document_processing",
      );

      streamAbortRef.current = streamChatMessages(
        sessionId,
        last_msg_id,
        (msg) => {
          setAgentMessages((prev) => [...prev, msg]);
        },
        () => {
          setAgentStatus("done");
          streamAbortRef.current = null;
          // Reload document so the page reflects the new linked_order_id
          fetchDocument().catch(() => {});
        },
        (err) => {
          setAgentError(err.message);
          setAgentStatus("error");
          streamAbortRef.current = null;
        },
      );
    } catch (error) {
      setAgentError(error instanceof Error ? error.message : String(error));
      setAgentStatus("error");
    }
  };

  // Human recovery path: save corrected fields, then retry the automatic
  // pipeline through the compatible create endpoint.
  //
  // Backend is async (ASYNC_CREATE_ORDER): create-order returns in <500ms
  // with status="matching" and the Gemini matching pipeline runs in the
  // background. We navigate to the order page immediately and let its
  // existing 2-second poll surface the status transition. This kills the
  // "click-and-wait-30s-feels-frozen" UX that prod users hit on docs the
  // classifier missed.
  //
  // `force=true` is safe here because this recovery card is shown only on a
  // document already classified as a purchase order.
  const handleConfirmCreate = async () => {
    if (!document) return;
    setSavingPreFlight(true);
    try {
      // 1. Persist any inline field edits the user made
      const updates: Record<string, string | null> = {};
      for (const [k, v] of Object.entries(preFlightFields)) {
        if (v.trim()) updates[k] = v.trim();
      }
      if (Object.keys(updates).length > 0) {
        const newPayload = await updateDocumentMetadata(document.id, updates);
        _payloadCache.set(document.id, newPayload);
        setPayload(newPayload);
        const refreshed = await getDocument(document.id);
        _docCache.set(document.id, refreshed);
        setDocument(refreshed);
      }

      // 2. Create the order (force=true) — backend returns in <500ms with
      //    status="matching".
      const order = await createOrderFromDocument(document.id, true);
      toast.success(`订单 #${order.id} 已创建，正在匹配产品…`);

      // 3. Jump straight to the order page. Its polling logic will track
      //    matching → ready/error without any extra work here.
      router.push(`/dashboard/orders/${order.id}`);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "建单失败");
      setSavingPreFlight(false);
    }
    // Note: no `finally` reset of savingPreFlight on the success path —
    // the navigation unmounts this view so the spinner clears naturally
    // with the page swap.
  };

  const handleAgentSubmit = async () => {
    const text = agentInput.trim();
    if (!text) return;
    setAgentInput("");
    await sendDocumentAgentMessage(text);
  };

  const cancelAgentRun = useCallback(async () => {
    if (!agentSessionId || !agentBusy) return;
    setAgentStatus("stopping");
    setAgentError(null);
    try {
      await cancelChatAgent(agentSessionId);
    } catch (error) {
      setAgentError(error instanceof Error ? error.message : "停止 Agent 失败");
      setAgentStatus("error");
    }
  }, [agentBusy, agentSessionId]);

  // Live elapsed-time ticker while agent is running
  useEffect(() => {
    if ((agentStatus !== "running" && agentStatus !== "stopping") || !agentStartedAt) return;
    const id = setInterval(() => {
      setAgentElapsed(Math.floor((Date.now() - agentStartedAt) / 1000));
    }, 1000);
    return () => clearInterval(id);
  }, [agentStatus, agentStartedAt]);

  // Auto-scroll the activity panel to the latest item
  useEffect(() => {
    if (!activityScrollRef.current) return;
    activityScrollRef.current.scrollTop = activityScrollRef.current.scrollHeight;
  }, [agentMessages]);

  // Tear down the SSE stream on unmount
  useEffect(() => {
    return () => {
      if (streamAbortRef.current) {
        streamAbortRef.current();
        streamAbortRef.current = null;
      }
    };
  }, []);

  if (loading) {
    return (
      <div className="mx-auto max-w-[1400px] px-8 py-10">
        <Skeleton className="mb-6 h-6 w-32" />
        <div className="grid gap-8 lg:grid-cols-[1fr_320px]">
          <Skeleton className="h-[760px] rounded-md" />
          <div className="space-y-6">
            <Skeleton className="h-32 rounded-md" />
            <Skeleton className="h-48 rounded-md" />
          </div>
        </div>
      </div>
    );
  }

  if (!document) {
    return (
      <div className="flex h-full items-center justify-center">
        <div className="space-y-3 text-center">
          <p className="text-sm text-muted-foreground">文档不存在</p>
          <Button variant="outline" size="sm" onClick={() => router.push("/dashboard/documents")}>
            返回文档列表
          </Button>
        </div>
      </div>
    );
  }

  const isPurchaseOrder = document.doc_type === "purchase_order";
  const isAwaitingAutomaticOrder =
    document.status === "extracted" &&
    isPurchaseOrder &&
    !document.linked_order_id &&
    !document.processing_error;
  const isProcessing =
    document.status === "uploaded" ||
    document.status === "extracting" ||
    isAwaitingAutomaticOrder;
  const isError = document.status === "error" || Boolean(
    isPurchaseOrder && !document.linked_order_id && document.processing_error,
  );

  // Master-data template heuristic — recurring user mistake: dragging
  // `product_upload_template.xlsx` (downloaded from the data-upload
  // page) into the document inbox, then forcing it as a PO. Pure
  // filename match because the template ships with a stable name; this
  // doesn't replace the back-end classifier but gives the user an
  // immediate "wrong place" signal before they tap "这是订单".
  const looksLikeMasterDataTemplate = (() => {
    const haystack = `${document.filename || ""} ${document.display_name || ""}`.toLowerCase();
    return (
      haystack.includes("product_upload_template") ||
      haystack.includes("product-upload-template") ||
      haystack.includes("产品上传模板") ||
      haystack.includes("数据上传模板")
    );
  })();
  const showMasterDataHint = looksLikeMasterDataTemplate && !document.linked_order_id;

  // Required fields for pre-flight check (must all be present to create order)
  const PRE_FLIGHT_FIELDS = [
    { key: "po_number", label: "PO 号" },
    { key: "ship_name", label: "船名" },
    { key: "delivery_date", label: "交货日期" },
  ] as const;
  const docMetadata = (document.extracted_data?.metadata || {}) as Record<string, unknown>;
  const preFlightComplete = PRE_FLIGHT_FIELDS.every(({ key }) => {
    const current = String(docMetadata[key] || "").trim();
    return current || preFlightFields[key]?.trim();
  });

  // Friendly labels for agent tool calls shown in the activity panel
  const TOOL_LABELS: Record<string, string> = {
    manage_document_order: "建立订单",
    manage_order: "验证订单",
    match_products: "匹配产品",
    manage_inquiry: "生成询价",
    get_context_package: "读取文档",
    use_skill: "执行流程",
    think: "分析中",
  };
  // Use stablePreviewUrl (locked) to prevent iframe reload on polls
  const previewUrl = stablePreviewUrl ?? resolvePreviewUrl(document.preview_url);
  const blockingFields = payload?.blocking_missing_fields || [];

  // ── Four-state primary action (commercial-grade design) ─────────────
  //
  // The button's existence and label depends on the system's confidence
  // that this document is something we can actually process. We explicitly
  // refuse to show a button for documents we can't handle — that would be
  // a false promise. Users can manually override the type if our
  // classification is wrong.
  //
  //   State A: high confidence PO + ready  → primary CTA "让 Agent 处理"
  //   State B: medium confidence (possibly) → confirm CTA + warning + override
  //   State C: low confidence / unknown    → no CTA + helper + override
  //   State D: already linked to order      → "前往订单 #N"
  //   (special: processing / error / missing fields / non-extracted excel)

  let primaryAction: React.ReactNode = null;
  let nextStepHint: string | null = null;
  let stateLabel: string | null = null;
  let showTypeOverride = false;

  if (isProcessing) {
    // Visible progress card so the user knows we're working — not a
    // dead spinner. Shows elapsed seconds because Gemini enrichment is
    // commonly 10-30s; without a counter users assume it's hung.
    stateLabel = "AI 提取中";
    primaryAction = (
      <div className="flex items-center gap-3 rounded-md border border-border/60 bg-muted/30 px-3 py-2.5">
        <Loader2 className="h-5 w-5 shrink-0 animate-spin text-primary" />
        <div className="flex-1 space-y-0.5">
          <div className="text-sm font-medium text-foreground">
            {isAwaitingAutomaticOrder ? "正在自动建立订单并继续处理" : "正在用 AI 提取订单信息"}
          </div>
          <div className="text-[11px] text-muted-foreground">
            {extractingElapsed > 0 ? `已用时 ${extractingElapsed}s · ` : ""}
            {isAwaitingAutomaticOrder
              ? "完成后将直接显示订单入口"
              : "通常 10-30 秒，页面会自动更新"}
          </div>
        </div>
      </div>
    );
    nextStepHint = null;
  } else if (isError) {
    // Error terminal — surface the message AND a retry button so the
    // user has a path forward without re-uploading.
    stateLabel = "提取失败";
    primaryAction = (
      <div className="space-y-2">
        <div className="rounded-md border border-destructive/40 bg-destructive/5 px-3 py-2 text-xs leading-5 text-destructive">
          {document.processing_error || "提取失败"}
        </div>
        <Button
          variant="outline"
          className="h-9 w-full gap-1.5"
          onClick={handleRetryExtract}
          disabled={retrying}
        >
          {retrying ? (
            <Loader2 className="h-4 w-4 animate-spin" />
          ) : (
            <RotateCcw className="h-4 w-4" />
          )}
          重新提取
        </Button>
      </div>
    );
    nextStepHint = null;
    showTypeOverride = true;
  } else if (document.linked_order_id) {
    // State D: already produced an order
    stateLabel = "已生成订单";
    primaryAction = (
      <Button
        className="h-9 w-full gap-1.5"
        onClick={() => router.push(`/dashboard/orders/${document.linked_order_id}`)}
      >
        前往订单 #{document.linked_order_id}
        <ArrowUpRight className="h-4 w-4" />
      </Button>
    );
  } else if (isPurchaseOrder && !agentBusy) {
    // State A: pre-flight card is rendered inline below — skip stateLabel/primaryAction here.
    showTypeOverride = true;
  } else if (confidenceVerdict === "possibly_purchase_order") {
    // State B: medium confidence, ambiguous
    stateLabel = confidenceScore !== null && confidenceMaxScore !== null
      ? `可能是采购订单 · 信心 ${confidenceScore}/${confidenceMaxScore}`
      : "可能是采购订单";
    nextStepHint = "系统不太确定，需要你确认";
    primaryAction = (
      <Button
        variant="outline"
        className="h-9 w-full gap-1.5"
        onClick={() => handleChangeDocType("purchase_order", { continueIfReady: true })}
        disabled={updatingType}
      >
        {updatingType ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
        确认为 PO 并继续
      </Button>
    );
    showTypeOverride = true;
  } else {
    // State C: low confidence / not_purchase_order / unknown
    stateLabel = "未识别为支持的类型";
    nextStepHint =
      "当前系统只支持自动处理采购订单。这份文档可以预览和查看提取的结构化内容，但不会自动建单。如果你确认这是 PO，请手动改类型。";
    showTypeOverride = true;
  }

  // Build a clean activity timeline by merging each `action` (tool call) with
  // its immediately-following `observation` (tool result). Thinking entries
  // become collapsible items. The agent's final `text` answer becomes a
  // distinct prose block at the end.
  type ActivityItem =
    | { id: number; kind: "tool_done"; toolName: string; durationMs: number }
    | { id: number; kind: "tool_error"; toolName: string; durationMs: number; errorMsg: string }
    | { id: number; kind: "tool_running"; toolName: string }
    | { id: number; kind: "thinking"; summary: string; full: string }
    | { id: number; kind: "answer"; content: string }
    | { id: number; kind: "error"; content: string };

  const activityItems: ActivityItem[] = [];
  for (let i = 0; i < agentMessages.length; i++) {
    const m = agentMessages[i];
    if (m.msg_type === "user_input") continue;
    if (m.msg_type === "observation" || m.msg_type === "error_observation") continue;

    if (m.msg_type === "action") {
      const toolName = (m.metadata?.tool_name as string) || "tool";
      // Find the next observation that comes BEFORE the next action
      let obs: ChatMessage | null = null;
      for (let j = i + 1; j < agentMessages.length; j++) {
        const n = agentMessages[j];
        if (n.msg_type === "action") break;
        if (n.msg_type === "observation" || n.msg_type === "error_observation") {
          obs = n;
          break;
        }
      }
      if (obs) {
        const durationMs = (obs.metadata?.duration_ms as number) || 0;
        if (obs.msg_type === "error_observation") {
          activityItems.push({
            id: m.id,
            kind: "tool_error",
            toolName,
            durationMs,
            errorMsg: obs.content,
          });
        } else {
          activityItems.push({ id: m.id, kind: "tool_done", toolName, durationMs });
        }
      } else {
        activityItems.push({ id: m.id, kind: "tool_running", toolName });
      }
      continue;
    }

    if (m.msg_type === "thinking") {
      activityItems.push({
        id: m.id,
        kind: "thinking",
        summary: (m.metadata?.summary as string) || m.content.slice(0, 80),
        full: m.content,
      });
      continue;
    }

    if (m.msg_type === "text" && m.role === "assistant") {
      activityItems.push({ id: m.id, kind: "answer", content: m.content });
      continue;
    }

    if (m.msg_type === "error") {
      activityItems.push({ id: m.id, kind: "error", content: m.content });
      continue;
    }
  }

  const showActivityPanel = agentStatus !== "idle" || activityItems.length > 0;

  return (
    <div className="h-full overflow-auto">
      <div className="mx-auto max-w-[1400px] px-8 py-8">
        {/* Top bar — minimal */}
        <div className="mb-6 flex items-center justify-between">
          <Button
            variant="ghost"
            size="sm"
            className="-ml-2 h-8 gap-1 px-2 text-muted-foreground hover:text-foreground"
            onClick={() => router.push("/dashboard/documents")}
          >
            <ArrowLeft className="h-3.5 w-3.5" />
            文档列表
          </Button>

          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                variant="ghost"
                size="icon"
                className="h-8 w-8 text-muted-foreground hover:text-foreground"
                aria-label="更多操作"
              >
                <MoreHorizontal className="h-4 w-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-32">
              <DropdownMenuItem
                onClick={() => setShowDeleteDialog(true)}
                className="text-red-600 focus:text-red-600 dark:text-red-400 dark:focus:text-red-400"
              >
                <Trash2 className="mr-2 h-3.5 w-3.5" />
                删除文档
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>

        {/* Two-column layout: preview left, action panel right */}
        <div className="grid gap-8 lg:grid-cols-[1fr_320px]">
          {/* LEFT: document preview */}
          <div className="space-y-6">
            <div className="overflow-hidden rounded-md border border-border/60 bg-background">
              {document.file_type === "pdf" && previewUrl ? (
                <iframe
                  title={`document-preview-${document.id}`}
                  src={`${previewUrl}#toolbar=0&navpanes=0&scrollbar=0&view=FitH`}
                  className="h-[760px] w-full"
                />
              ) : document.file_type?.startsWith("image/") && previewUrl ? (
                <div className="p-4">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={previewUrl}
                    alt={document.filename}
                    className="block h-auto w-full rounded"
                    draggable={false}
                  />
                </div>
              ) : isSpreadsheetType(document.file_type) && previewUrl ? (
                // Excel / CSV preview via SheetJS. preview_url is a signed
                // Supabase URL — fetch returns the original binary.
                <div className="p-4">
                  <SpreadsheetViewer
                    filename={document.filename}
                    fetchFile={async () => {
                      const resp = await fetch(previewUrl);
                      if (!resp.ok) {
                        throw new Error(`文件下载失败 (HTTP ${resp.status})`);
                      }
                      return resp.arrayBuffer();
                    }}
                  />
                </div>
              ) : previewUrl ? (
                <div className="space-y-3 p-6 text-sm">
                  <div className="text-muted-foreground">当前文件类型暂无内嵌预览</div>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => window.open(previewUrl, "_blank", "noopener,noreferrer")}
                  >
                    打开原始文件
                  </Button>
                </div>
              ) : (
                <div className="p-6 text-sm text-muted-foreground">暂无原始文件预览</div>
              )}
            </div>

            {/* AI summary + tags. Three styles:
                - System (file_type:..., doc_type:...) — muted/mono
                - LLM topic tags (celebrity-cruise) — light bg
                - User-added tags — blue with X to remove
                Always render the card — even on a doc with no summary
                yet, the user might still want to add tags. */}
            <DocumentSummaryCard
              summary={document.summary}
              tags={document.tags || []}
              userTags={document.user_tags || []}
              onAddTag={async (tag) => {
                const updated = await addUserTag(document.id, tag);
                _docCache.set(document.id, updated);
                setDocument(updated);
              }}
              onRemoveTag={async (tag) => {
                const updated = await removeUserTag(document.id, tag);
                _docCache.set(document.id, updated);
                setDocument(updated);
              }}
            />


            {/* Markdown rendering of the extractor output. Single source of
                truth for "what did the system pull out of this file". */}
            {document.content_markdown ? (
              <div className="space-y-3">
                {extractionError && (
                  <div className="rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800 dark:border-amber-800/40 dark:bg-amber-950/30 dark:text-amber-300">
                    <span className="font-medium">结构化提取未完成：</span>
                    {extractionError.kind === "truncated"
                      ? "文档内容过长，AI 输出被截断，当前展示为基础提取结果。"
                      : extractionError.message}
                  </div>
                )}
                <Collapsible open={extractedOpen} onOpenChange={setExtractedOpen}>
                  <CollapsibleTrigger asChild>
                    <button
                      type="button"
                      className="flex w-full items-center justify-between rounded-md border border-border/60 px-4 py-3 text-sm font-medium hover:bg-muted/40"
                    >
                      <span>系统提取的结构化内容</span>
                      {extractedOpen ? (
                        <ChevronDown className="h-4 w-4 text-muted-foreground" />
                      ) : (
                        <ChevronRight className="h-4 w-4 text-muted-foreground" />
                      )}
                    </button>
                  </CollapsibleTrigger>
                  <CollapsibleContent className="mt-3 rounded-md border border-border/60 p-5">
                    <MarkdownContent content={document.content_markdown} />
                  </CollapsibleContent>
                </Collapsible>
              </div>
            ) : null}
          </div>

          {/* RIGHT: action panel — flat, no nested cards */}
          <aside className="space-y-6">
            {/* Title block — click h1 to rename. display_name takes
                precedence when set; original filename is always visible
                below as audit anchor. */}
            <div>
              <EditableDocTitle
                doc={document}
                onSaved={(updated) => {
                  _docCache.set(updated.id, updated);
                  setDocument(updated);
                }}
              />
              <div className="mt-2 flex items-center gap-3">
                <StatusDot status={document.status} />
                <span className="text-xs text-muted-foreground">
                  {formatTime(document.created_at)}
                </span>
              </div>
              {(document.uploader_name || document.uploader_email) ? (
                <div
                  className="mt-1 text-xs text-muted-foreground"
                  title={document.uploader_email ?? undefined}
                >
                  上传者:{" "}
                  {document.uploader_name || document.uploader_email}
                </div>
              ) : null}
              <DocumentFolderPicker
                doc={document}
                onMoved={(updated) => {
                  _docCache.set(updated.id, updated);
                  setDocument(updated);
                }}
              />
            </div>

            {/* Metadata description list + inline edit */}
            {(metadataPairs.length > 0 || document.status === "extracted") ? (
              <div className="space-y-2 border-t border-border/60 pt-5">
                <div className="flex items-center justify-between mb-1">
                  <span className="text-xs text-muted-foreground font-medium">提取字段</span>
                  {document.status === "extracted" && !editingMeta && (
                    <button
                      onClick={startEditMeta}
                      className="flex items-center gap-1 text-[11px] text-muted-foreground hover:text-foreground transition-colors"
                    >
                      <Pencil className="h-3 w-3" />
                      编辑
                    </button>
                  )}
                  {editingMeta && (
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => setEditingMeta(false)}
                        className="text-[11px] text-muted-foreground hover:text-foreground"
                        disabled={savingMeta}
                      >
                        取消
                      </button>
                      <button
                        onClick={handleSaveMeta}
                        className="flex items-center gap-1 text-[11px] text-emerald-600 hover:text-emerald-500 font-medium"
                        disabled={savingMeta}
                      >
                        {savingMeta ? <Loader2 className="h-3 w-3 animate-spin" /> : <Check className="h-3 w-3" />}
                        保存
                      </button>
                    </div>
                  )}
                </div>

                {editingMeta ? (
                  <div className="space-y-2">
                    {EDITABLE_FIELDS.map(({ key, label }) => (
                      <div key={key} className="flex items-center gap-2">
                        <label className="w-20 shrink-0 text-[11px] text-muted-foreground text-right">{label}</label>
                        <Input
                          value={editFields[key] ?? ""}
                          onChange={(e) => setEditFields(prev => ({ ...prev, [key]: e.target.value }))}
                          className="h-7 text-xs"
                          placeholder="—"
                          disabled={savingMeta}
                        />
                      </div>
                    ))}
                  </div>
                ) : (
                  <dl className="space-y-2.5 text-sm">
                    {metadataPairs
                      .filter(([key]) => key !== "extra_fields")
                      .map(([key, value]) => (
                        <div key={key} className="flex items-baseline justify-between gap-4">
                          <dt className="text-xs text-muted-foreground">
                            {META_LABELS[key] || key}
                          </dt>
                          <dd className="text-right font-medium tabular-nums">
                            {formatMetaValue(key, value)}
                          </dd>
                        </div>
                      ))}
                    {productCount > 0 ? (
                      <div className="flex items-baseline justify-between gap-4">
                        <dt className="text-xs text-muted-foreground">产品数</dt>
                        <dd className="text-right font-medium tabular-nums">{productCount}</dd>
                      </div>
                    ) : null}
                  </dl>
                )}
              </div>
            ) : null}

            {/* Agent activity panel — visible when agent is running OR has run */}
            {showActivityPanel ? (
              <div className="space-y-3 border-t border-border/60 pt-5">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 text-xs">
                    {agentStatus === "running" || agentStatus === "stopping" ? (
                      <Loader2 className="h-3 w-3 animate-spin text-foreground/70" />
                    ) : agentStatus === "error" ? (
                      <X className="h-3 w-3 text-red-500" />
                    ) : (
                      <Check className="h-3 w-3 text-emerald-600" />
                    )}
                    <span className="font-medium">
                      {agentStatus === "running"
                        ? "Agent 处理中"
                        : agentStatus === "stopping"
                          ? "正在停止 Agent"
                        : agentStatus === "error"
                          ? "处理失败"
                          : "处理完成"}
                    </span>
                    <span className="text-muted-foreground">
                      · {(agentStatus === "running" || agentStatus === "stopping")
                        ? agentElapsed
                        : Math.floor((Date.now() - (agentStartedAt || Date.now())) / 1000)}s
                    </span>
                  </div>
                  {agentBusy ? (
                    <Button
                      type="button"
                      size="sm"
                      variant="destructive"
                      onClick={() => cancelAgentRun().catch(() => {})}
                      disabled={agentStatus === "stopping"}
                      className="h-8 px-3"
                    >
                      {agentStatus === "stopping" ? "正在停止…" : "停止 Agent"}
                    </Button>
                  ) : null}
                </div>

                {agentBusy ? (
                  <div className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-xs leading-5 text-red-700">
                    {agentStatus === "stopping"
                      ? "已向后端发送停止信号，当前任务会在安全点尽快终止。"
                      : "Agent 正在运行，会继续消耗后端模型调用；如需立即终止，请点“停止 Agent”。"}
                  </div>
                ) : null}

                <div
                  ref={activityScrollRef}
                  className="max-h-[420px] space-y-1.5 overflow-y-auto rounded-md border border-border/60 bg-muted/20 p-3"
                >
                  {activityItems.length === 0 ? (
                    <div className="py-2 text-xs text-muted-foreground">等待 Agent 启动…</div>
                  ) : (
                    activityItems.map((item) => {
                      if (item.kind === "tool_done") {
                        return (
                          <div key={item.id} className="flex items-center gap-2 text-xs leading-5">
                            <Check className="h-3 w-3 shrink-0 text-emerald-600" />
                            <span className="text-[11px] text-foreground/90">
                              {TOOL_LABELS[item.toolName] || item.toolName}
                            </span>
                            <span className="text-muted-foreground">
                              · {(item.durationMs / 1000).toFixed(1)}s
                            </span>
                          </div>
                        );
                      }
                      if (item.kind === "tool_running") {
                        return (
                          <div key={item.id} className="flex items-center gap-2 text-xs leading-5">
                            <Loader2 className="h-3 w-3 shrink-0 animate-spin text-muted-foreground" />
                            <span className="text-[11px] text-foreground/90">
                              {TOOL_LABELS[item.toolName] || item.toolName}
                            </span>
                            <span className="text-muted-foreground">· 处理中</span>
                          </div>
                        );
                      }
                      if (item.kind === "tool_error") {
                        return (
                          <div key={item.id} className="space-y-0.5 text-xs leading-5">
                            <div className="flex items-center gap-2">
                              <X className="h-3 w-3 shrink-0 text-red-500" />
                              <span className="text-[11px] text-foreground/90">
                                {TOOL_LABELS[item.toolName] || item.toolName}
                              </span>
                              <span className="text-muted-foreground">
                                · {(item.durationMs / 1000).toFixed(1)}s
                              </span>
                            </div>
                            <div className="ml-5 text-red-600 dark:text-red-400">
                              {item.errorMsg.slice(0, 200)}
                            </div>
                          </div>
                        );
                      }
                      if (item.kind === "thinking") {
                        return (
                          <details key={item.id} className="group text-xs leading-5">
                            <summary className="flex cursor-pointer items-center gap-1.5 text-muted-foreground hover:text-foreground">
                              <ChevronRight className="h-3 w-3 transition-transform group-open:rotate-90" />
                              <span className="text-foreground/60">思考</span>
                              <span className="truncate">· {item.summary}</span>
                            </summary>
                            <pre className="ml-4 mt-1.5 whitespace-pre-wrap font-sans text-xs leading-5 text-muted-foreground">
                              {item.full}
                            </pre>
                          </details>
                        );
                      }
                      if (item.kind === "answer") {
                        return (
                          <div
                            key={item.id}
                            className="mt-2 rounded-md border border-border/60 bg-background px-3 py-2 text-xs leading-5"
                          >
                            <MarkdownContent content={item.content} />
                          </div>
                        );
                      }
                      if (item.kind === "error") {
                        return (
                          <div key={item.id} className="flex items-start gap-2 text-xs leading-5">
                            <X className="h-3 w-3 mt-0.5 shrink-0 text-red-500" />
                            <span className="text-red-600 dark:text-red-400">{item.content}</span>
                          </div>
                        );
                      }
                      return null;
                    })
                  )}
                </div>

                {agentError ? (
                  <p className="text-xs text-red-600 dark:text-red-400">{agentError}</p>
                ) : null}
              </div>
            ) : null}

            {/* Human recovery only. Normal PO uploads create the Order automatically. */}
            {isPurchaseOrder && !document.linked_order_id && !agentBusy && document.processing_error ? (
              <div className="space-y-3 border-t border-border/60 pt-5">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-medium">人工修正后重试</span>
                  {productCount > 0 && (
                    <span className="text-[11px] text-muted-foreground">{productCount} 个产品</span>
                  )}
                </div>

                <div className="space-y-2">
                  {PRE_FLIGHT_FIELDS.map(({ key, label }) => {
                    const current = String(docMetadata[key] || "").trim();
                    const missing = !current;
                    return (
                      <div key={key} className="flex items-center gap-2 text-[11px]">
                        {missing ? (
                          <span className="shrink-0 text-amber-500">⚠</span>
                        ) : (
                          <Check className="h-3 w-3 shrink-0 text-emerald-600" />
                        )}
                        <span className="w-16 shrink-0 text-muted-foreground">{label}</span>
                        {missing ? (
                          <Input
                            value={preFlightFields[key] ?? ""}
                            onChange={(e) =>
                              setPreFlightFields((prev) => ({ ...prev, [key]: e.target.value }))
                            }
                            className="h-6 flex-1 text-[11px]"
                            placeholder={`填写${label}`}
                            disabled={savingPreFlight}
                          />
                        ) : (
                          <span className="flex-1 truncate font-medium">{current}</span>
                        )}
                      </div>
                    );
                  })}
                </div>

                {productCount === 0 && (
                  <p className="text-[11px] text-amber-600">未提取到产品列表，请先修正或重新提取</p>
                )}

                <Button
                  className="h-9 w-full"
                  disabled={!preFlightComplete || savingPreFlight}
                  onClick={() => handleConfirmCreate().catch(() => {})}
                >
                  {savingPreFlight ? (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  ) : null}
                  保存并重试自动流程
                </Button>

                {showTypeOverride && (
                  <div className="text-[11px] text-muted-foreground">
                    手动指定类型：
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <button
                          type="button"
                          className="ml-1 inline-flex items-center gap-1 font-medium text-foreground/80 underline decoration-dotted underline-offset-2 hover:text-foreground"
                          disabled={updatingType}
                        >
                          {document.doc_type === "purchase_order" ? "采购订单" : document.doc_type || "—"}
                          {updatingType ? (
                            <Loader2 className="h-3 w-3 animate-spin" />
                          ) : (
                            <ChevronDown className="h-3 w-3" />
                          )}
                        </button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="start" className="w-40">
                        <DropdownMenuItem
                          onClick={() => handleChangeDocType("purchase_order")}
                          disabled={document.doc_type === "purchase_order" || updatingType}
                        >
                          采购订单
                        </DropdownMenuItem>
                        <DropdownMenuItem
                          onClick={() => handleChangeDocType("unknown")}
                          disabled={document.doc_type === "unknown" || updatingType}
                        >
                          未识别 / 其他
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </div>
                )}
              </div>
            ) : null}

            {/* Master-data template misroute warning — sits above the
                primary action so the user sees it before clicking
                "这是订单" on a file that isn't an order. */}
            {!agentBusy && showMasterDataHint ? (
              <div className="space-y-2 rounded-md border border-amber-500/40 bg-amber-500/5 px-3 py-2.5 text-xs leading-5 text-amber-900 dark:text-amber-200">
                <div className="font-medium">看起来这是产品上传模板</div>
                <p className="text-amber-800/80 dark:text-amber-200/80">
                  这个文件名是数据上传的标准模板，不是采购订单。继续按订单处理会让 AI 提取失败。建议改用「数据上传」页面批量导入产品。
                </p>
                <Button
                  variant="outline"
                  size="sm"
                  className="h-7 gap-1 border-amber-500/50 text-amber-900 hover:bg-amber-500/10 dark:text-amber-200"
                  onClick={() => router.push("/dashboard/data-upload")}
                >
                  前往数据上传
                  <ArrowUpRight className="h-3.5 w-3.5" />
                </Button>
              </div>
            ) : null}

            {/* Primary action + state label + hint + optional type override
                (hidden while agent is running so the activity panel takes
                full attention) */}
            {!agentBusy && (primaryAction || nextStepHint || stateLabel) ? (
              <div className="space-y-3 border-t border-border/60 pt-5">
                {stateLabel ? (
                  <div className="text-[11px] uppercase tracking-wide text-muted-foreground">
                    {stateLabel}
                  </div>
                ) : null}
                {primaryAction}
                {nextStepHint ? (
                  <p className="text-xs leading-5 text-muted-foreground">{nextStepHint}</p>
                ) : null}
                {showTypeOverride && !document.linked_order_id ? (
                  <div className="pt-1 text-xs text-muted-foreground">
                    手动指定类型：
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <button
                          type="button"
                          className="ml-1 inline-flex items-center gap-1 font-medium text-foreground/80 underline decoration-dotted underline-offset-2 hover:text-foreground"
                          disabled={updatingType}
                        >
                          {document.doc_type === "purchase_order"
                            ? "采购订单"
                            : document.doc_type === "unknown"
                              ? "未识别"
                              : document.doc_type || "—"}
                          {updatingType ? (
                            <Loader2 className="h-3 w-3 animate-spin" />
                          ) : (
                            <ChevronDown className="h-3 w-3" />
                          )}
                        </button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="start" className="w-40">
                        <DropdownMenuItem
                          onClick={() => handleChangeDocType("purchase_order")}
                          disabled={document.doc_type === "purchase_order" || updatingType}
                        >
                          采购订单
                        </DropdownMenuItem>
                        <DropdownMenuItem
                          onClick={() => handleChangeDocType("unknown")}
                          disabled={document.doc_type === "unknown" || updatingType}
                        >
                          未识别 / 其他
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </div>
                ) : null}
              </div>
            ) : null}

            {/* Document type / id — small footer info */}
            <div className="space-y-1.5 border-t border-border/60 pt-5 text-xs text-muted-foreground">
              <div className="flex justify-between">
                <span>文档 ID</span>
                <span className="font-medium text-foreground/80">{document.id}</span>
              </div>
              <div className="flex justify-between">
                <span>类型</span>
                <span className="font-medium text-foreground/80">
                  {document.doc_type === "purchase_order"
                    ? "采购订单"
                    : document.doc_type === "unknown"
                      ? "未识别"
                      : document.doc_type || "—"}
                </span>
              </div>
              <div className="flex justify-between">
                <span>文件类型</span>
                <span className="font-medium uppercase text-foreground/80">
                  {document.file_type}
                </span>
              </div>
            </div>
          </aside>
        </div>
      </div>

      <AlertDialog
        open={showDeleteDialog}
        onOpenChange={(open) => {
          if (!open && !deleting) setShowDeleteDialog(false);
        }}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>删除文档</AlertDialogTitle>
            <AlertDialogDescription asChild>
              <div className="space-y-2 text-sm leading-6">
                <div>
                  确认要删除 <span className="font-medium text-foreground">{document.filename}</span> 吗？此操作不可撤销。
                </div>
                {document.linked_order_id ? (
                  <div className="text-muted-foreground">
                    该文档已生成订单 #{document.linked_order_id}。删除后订单会保留，但与此源文档解除关联。
                  </div>
                ) : null}
              </div>
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={deleting}>取消</AlertDialogCancel>
            <AlertDialogAction
              onClick={(e) => {
                e.preventDefault();
                handleDelete();
              }}
              disabled={deleting}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              {deleting ? <Loader2 className="mr-1.5 h-4 w-4 animate-spin" /> : null}
              {document.linked_order_id ? "强制删除" : "删除"}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}


/**
 * Build the breadcrumb path from leaf → root by walking parent_folder_id.
 * Returns ordered list root-first. Cycle-safe (capped at depth 12).
 */
function buildFolderPath(
  leafId: number | null,
  folders: DocumentFolder[],
): DocumentFolder[] {
  if (leafId == null) return [];
  const byId = new Map<number, DocumentFolder>();
  for (const f of folders) byId.set(f.id, f);
  const path: DocumentFolder[] = [];
  let cur: DocumentFolder | undefined = byId.get(leafId);
  const seen = new Set<number>();
  let safety = 0;
  while (cur && !seen.has(cur.id) && safety < 12) {
    seen.add(cur.id);
    path.unshift(cur);
    cur = cur.parent_folder_id != null ? byId.get(cur.parent_folder_id) : undefined;
    safety++;
  }
  return path;
}

// DocumentFolderPicker — shows the full breadcrumb path (P3B-F4
// 2026-06-22 UX) and lets the user move the doc. Pre-loads folders
// on mount so the breadcrumb renders immediately rather than the
// previous "Folder Name only after dropdown opens" pattern.
function DocumentFolderPicker({
  doc,
  onMoved,
}: {
  doc: DocumentDetail;
  onMoved: (updated: DocumentDetail) => void;
}) {
  const [folders, setFolders] = useState<DocumentFolder[]>([]);
  const [open, setOpen] = useState(false);
  const [moving, setMoving] = useState(false);

  // Preload folders so the breadcrumb is correct on first paint.
  // Cheap call — list is bounded.
  useEffect(() => {
    listFolders().then(setFolders).catch(() => {});
  }, []);

  const path = buildFolderPath(doc.folder_id, folders);

  const move = async (target: number | null) => {
    if (target === doc.folder_id) return;
    setMoving(true);
    try {
      const updated = await moveDocumentToFolder(doc.id, target);
      onMoved(updated);
      const targetLabel =
        target === null
          ? "未分类"
          : folders.find((f) => f.id === target)?.name ?? "目标文件夹";
      toast.success(`已移动到「${targetLabel}」`);
      setOpen(false);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "移动失败");
    } finally {
      setMoving(false);
    }
  };

  return (
    <DropdownMenu open={open} onOpenChange={setOpen}>
      <DropdownMenuTrigger asChild>
        <button
          className="mt-2 inline-flex items-center gap-0.5 text-[11px] text-muted-foreground hover:text-foreground transition-colors disabled:opacity-50 max-w-full"
          disabled={moving}
          title="移动到文件夹"
        >
          <Folder className="h-3 w-3 shrink-0 mr-0.5" />
          {path.length === 0 ? (
            <span className="truncate">未分类</span>
          ) : (
            path.map((f, i) => {
              const dot = folderColor(f);
              return (
                <span key={f.id} className="inline-flex items-center min-w-0 gap-1">
                  {i > 0 && (
                    <span className="mx-0.5 text-muted-foreground/40 shrink-0">
                      ›
                    </span>
                  )}
                  {dot ? (
                    <span
                      className="inline-block h-1.5 w-1.5 shrink-0 rounded-full"
                      style={{ backgroundColor: dot }}
                      aria-hidden
                    />
                  ) : null}
                  <span className="truncate max-w-[120px]" title={f.name}>
                    {f.name}
                  </span>
                </span>
              );
            })
          )}
          <ChevronDown className="h-3 w-3 shrink-0 ml-0.5" />
        </button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="start" className="max-h-[300px] overflow-y-auto w-56">
        <DropdownMenuItem onClick={() => move(null)}>
          <Folder className="mr-1.5 h-3 w-3 text-muted-foreground/40" />
          <span className="text-muted-foreground">未分类</span>
          {doc.folder_id === null && <Check className="ml-auto h-3 w-3" />}
        </DropdownMenuItem>
        {folders.length === 0 ? (
          <div className="px-2 py-1.5 text-[11px] text-muted-foreground/60">
            还没有文件夹
          </div>
        ) : (
          folders.map((f) => {
            const dot = folderColor(f);
            return (
              <DropdownMenuItem key={f.id} onClick={() => move(f.id)}>
                {dot ? (
                  <span
                    className="mr-1.5 inline-block h-2 w-2 shrink-0 rounded-full"
                    style={{ backgroundColor: dot }}
                    aria-hidden
                  />
                ) : (
                  <Folder className="mr-1.5 h-3 w-3 text-muted-foreground/70" />
                )}
                <span className="truncate">{f.name}</span>
                {doc.folder_id === f.id && <Check className="ml-auto h-3 w-3" />}
              </DropdownMenuItem>
            );
          })
        )}
      </DropdownMenuContent>
    </DropdownMenu>
  );
}


// EditableDocTitle — title shows `display_name ?? filename` with a click
// affordance to rename. Esc cancels, Enter saves, blur saves. Empty
// input clears `display_name`, which reverts to filename. The original
// filename is always visible as a smaller line below the title so the
// audit trail isn't lost when a user renames.
function EditableDocTitle({
  doc,
  onSaved,
}: {
  doc: DocumentDetail;
  onSaved: (updated: DocumentDetail) => void;
}) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(doc.display_name ?? "");
  const [saving, setSaving] = useState(false);
  const renamed = !!doc.display_name && doc.display_name !== doc.filename;

  const commit = async () => {
    if (saving) return;
    const next = draft.trim();
    // No-op if nothing changed (covers "open editor, click away").
    const before = (doc.display_name ?? "").trim();
    if (next === before) {
      setEditing(false);
      return;
    }
    setSaving(true);
    try {
      const updated = await renameDocument(doc.id, next || null);
      onSaved(updated);
      setEditing(false);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "重命名失败");
    } finally {
      setSaving(false);
    }
  };

  if (editing) {
    return (
      <div>
        <Input
          autoFocus
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          onBlur={() => void commit()}
          onKeyDown={(e) => {
            if (e.key === "Enter") {
              e.preventDefault();
              void commit();
            } else if (e.key === "Escape") {
              setDraft(doc.display_name ?? "");
              setEditing(false);
            }
          }}
          maxLength={255}
          placeholder={doc.filename}
          className="h-8 text-base font-semibold"
          disabled={saving}
        />
        <p className="mt-1 text-[11px] text-muted-foreground/70">
          Enter 保存，Esc 取消，留空恢复原文件名
        </p>
      </div>
    );
  }

  return (
    <div className="group">
      <button
        onClick={() => {
          setDraft(doc.display_name ?? "");
          setEditing(true);
        }}
        className="w-full text-left"
        title="点击重命名"
      >
        <h1 className="break-all text-base font-semibold leading-snug hover:text-foreground/80 transition-colors">
          {doc.display_name || doc.filename}
          <Pencil className="ml-1 inline h-3 w-3 text-muted-foreground/40 group-hover:text-muted-foreground transition-colors" />
        </h1>
      </button>
      {renamed && (
        <p
          className="mt-0.5 break-all text-[11px] text-muted-foreground/60"
          title="原文件名（不可修改）"
        >
          {doc.filename}
        </p>
      )}
    </div>
  );
}
