"use client";

/**
 * GenericTable — universal artifact renderer for any agent-supplied
 * tabular data (weather, search results, ad-hoc listings).
 *
 * Unlike UploadDiffViewer (which fetches data from a REST endpoint
 * keyed by reference IDs), this component receives `columns` + `rows`
 * directly from the agent's artifact event payload. The leaf values
 * come from the LLM — so the panel header is explicitly labelled
 * "AI-generated content" to set user trust expectations.
 *
 * Trade-off documented in docs/current_progress/2026-05-19/agent-html-
 * interaction-architecture.md: domain components get the no-hallucination
 * guarantee (backend fetch); generic ones gain reach at the cost of
 * inline data, mitigated by the 100-row cap + visible badge.
 */

interface Column {
  key: string;
  label: string;
  align?: "left" | "right" | "center";
}

interface Props {
  title: string;
  columns: Column[];
  rows: Array<Record<string, unknown>>;
  caption?: string;
  highlightKey?: string;
}

function renderValue(v: unknown): string {
  if (v === null || v === undefined) return "—";
  if (typeof v === "string" || typeof v === "number" || typeof v === "boolean")
    return String(v);
  return JSON.stringify(v);
}

export function GenericTable({
  title,
  columns,
  rows,
  caption,
  highlightKey,
}: Props) {
  if (!Array.isArray(columns) || columns.length === 0) {
    return (
      <p className="text-xs text-destructive p-3">
        generic_table: missing or empty `columns`
      </p>
    );
  }

  return (
    <div className="space-y-2">
      <div className="flex items-baseline gap-2">
        <h3 className="text-sm font-semibold">{title}</h3>
        <span
          className="text-[10px] px-1.5 py-0.5 rounded bg-amber-100 text-amber-900 dark:bg-amber-900/30 dark:text-amber-200"
          title="The rows in this table were generated by the AI agent rather than fetched from a verified backend source. Cross-check sensitive values."
        >
          🤖 AI-generated content
        </span>
      </div>
      {caption && (
        <p className="text-xs text-muted-foreground">{caption}</p>
      )}

      <div className="max-h-[480px] overflow-auto rounded-md border border-border/60">
        <table className="min-w-full text-xs">
          <thead className="bg-zinc-50 dark:bg-zinc-900 sticky top-0">
            <tr>
              {columns.map((col) => (
                <th
                  key={col.key}
                  className={`px-2 py-1.5 font-medium text-${col.align || "left"} whitespace-nowrap`}
                >
                  {col.label}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.length === 0 ? (
              <tr>
                <td
                  colSpan={columns.length}
                  className="px-2 py-3 text-center text-muted-foreground"
                >
                  (no rows)
                </td>
              </tr>
            ) : (
              rows.map((row, i) => (
                <tr
                  key={i}
                  className="even:bg-zinc-50/50 dark:even:bg-zinc-900/20"
                >
                  {columns.map((col) => {
                    const isHighlight = highlightKey === col.key;
                    return (
                      <td
                        key={col.key}
                        className={
                          "px-2 py-1.5 text-" +
                          (col.align || "left") +
                          (isHighlight
                            ? " font-medium text-foreground"
                            : "")
                        }
                      >
                        {renderValue(row[col.key])}
                      </td>
                    );
                  })}
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <p className="text-[10px] text-muted-foreground">
        {rows.length} 行 · 由 AI 即时生成；如需权威数据请通过域内工具核对
      </p>
    </div>
  );
}
